### ISSUE TITLE
Port 80 not recommended for production

### ISSUE THREAD

**Issue by therealmarv** [indiehosters/nextcloud#6]
In your readme you write:

> You can now access your instance on the port 80 of the IP of your machine (not recommended for production).

So what is the best way for running in production? How can I change the port?

**Comment by pierreozoux** [comment]
You have to read the full readme :)

https://github.com/indiehosters/nextcloud#access-it-from-internet

**Comment by pierreozoux** [comment]
Let me know if you have doubts regarding this :)
